### PR TITLE
Fix the caching problem by storing cached bots with fake IDs

### PR DESCRIPTION
**Pull request by Brilliand**
This allows bot code to be reloaded by entering the true gist ID, as discussed in SE chat.

I've also updated the cached versions of some of my own bots.

### CODE REVIEW

**Comment by AJFaraday** [comment]
Just one thing needed here, the stored gists won't be used, unless a user manually adds '-stored' in the url or gist id field.

On `/lib/api_ui.js`, line 18, we need to add '-stored' to the value in order to use the stored gists on a change of the select.

**Comment by Brilliand** [comment]
Isn't it sufficient to add "-stored" to the end of every gist ID config/bots.js?

**Comment by AJFaraday** [comment]
Actually, it might be... I'll check it when I get a break.

**Comment by AJFaraday** [comment]
My mistake, it worked like a charm! Thank you for fixing this (people really did't like the caching :p)

**Pull request merged**
